### ISSUE TITLE
UnicodeEncodeError when doing En-De prediction

### ISSUE THREAD

**Issue by okuchaiev** [google/seq2seq#128]
After training En-De model, I tried running inference task and got UnicodeEncodeError:
My training and prediction scripts are attached.

Error:
`Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/okuchaiev/repos/seq2seq/bin/infer.py", line 129, in <module>
    tf.app.run()
  File "/home/okuchaiev/repos/tensorflow/_python_build/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/home/okuchaiev/repos/seq2seq/bin/infer.py", line 125, in main
    sess.run([])
  File "/home/okuchaiev/repos/tensorflow/_python_build/tensorflow/python/training/monitored_session.py", line 462, in run
    run_metadata=run_metadata)
  File "/home/okuchaiev/repos/tensorflow/_python_build/tensorflow/python/training/monitored_session.py", line 786, in run
    run_metadata=run_metadata)
  File "/home/okuchaiev/repos/tensorflow/_python_build/tensorflow/python/training/monitored_session.py", line 744, in run
    return self._sess.run(*args, **kwargs)
  File "/home/okuchaiev/repos/tensorflow/_python_build/tensorflow/python/training/monitored_session.py", line 899, in run
    run_metadata=run_metadata))
  File "/home/okuchaiev/repos/seq2seq/seq2seq/tasks/decode_text.py", line 188, in after_run
    print(sent)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf6' in position 6: ordinal not in range(128)
`
************
My prediction script:

export CUDA_VISIBLE_DEVICES=0
export MODEL_DIR=/media/okuchaiev/D2/Workspace/seq2seq/Exp1_toy/nmt_tutorial_small
export PRED_DIR=${MODEL_DIR}/pred
export DATA_PATH=/home/okuchaiev/nmt_data/wmt16_de_en
export DEV_SOURCES=${DATA_PATH}/newstest2013.tok.bpe.32000.en

mkdir -p ${PRED_DIR}

python -m ${HOME}/repos/seq2seq/bin/infer \
  --tasks "
    - class: DecodeText" \
  --model_dir $MODEL_DIR \
  --input_pipeline "
    class: ParallelTextInputPipeline
    params:
      source_files:
        - $DEV_SOURCES" \
  \>  ${PRED_DIR}/predictions.txt

**Comment by skyw** [comment]
a brute fix is change last line of decode_test.py to
print(sent.encode('ascii', 'ignore'))

**Comment by okuchaiev** [comment]
This PR fixes the issue: 
Change mentioned by @skyw above fixes the issue.
Also, doing 

> export PYTHONIOENCODING=UTF-8 
without changing the code fixes issue.

Also, see this PR: https://github.com/google/seq2seq/pull/96
Closing
