### ISSUE TITLE
ValueError: Cannot infer Tensor's rank

### ISSUE THREAD

**Issue by wingsbr** [google/seq2seq#151]
I'm attempting to adapt this for speech recognition, but am having difficulty doing so.

I have already stored the audio data and labels as SequenceExamples in TFRecord files with the following structure:

```
feat_dict = {"feats": tf.train.FeatureList(feature=feats_list)}
sequence_feats = tf.train.FeatureLists(feature_list=feat_dict)
        
len_feat = tf.train.Feature(int64_list=tf.train.Int64List(value=[size]))
label_feat = tf.train.Feature(int64_list=tf.train.Int64List(value=labels[key]))
key_feat = tf.train.Feature(bytes_list=tf.train.BytesList(value=[key]))
context_feats = tf.train.Features(feature={"seq_len": len_feat, "labels": label_feat, "key": key_feat})

example = tf.train.SequenceExample(context=context_feats, feature_lists=sequence_feats)
```

I created a new pipeline based on the ImageCaptioningInputPipeline, but with the following changes:

```
context_keys_to_features = {
    "labels": tf.FixedLenFeature([], dtype=tf.int64),
    "seq_len": tf.FixedLenFeature([], dtype=tf.int64)
}

sequence_keys_to_features = {
    "feats": tf.FixedLenSequenceFeature([], dtype=tf.float32)
}

items_to_handlers = {
    "feats": tfexample_decoder.Tensor("feats"), 
    "target_ids": tfexample_decoder.Tensor("labels"),
    "target_tokens": tfexample_decoder.Tensor("labels"), 
    "target_len": tfexample_decoder.ItemHandlerCallback(keys=["labels"], func=lambda x: tf.size(x["labels"]))
}
```

However, when I attempt to train with it, I'm getting the following error:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/u2/bin/seq2seq/bin/train.py", line 276, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/u2/bin/seq2seq/bin/train.py", line 271, in main
    schedule=FLAGS.schedule)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/learn_runner.py", line 111, in run
    return _execute_schedule(experiment, schedule)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/learn_runner.py", line 46, in _execute_schedule
    return task()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/experiment.py", line 431, in train_and_evaluate
    self.train(delay_secs=0)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/experiment.py", line 230, in train
    monitors=self._train_monitors + extra_hooks)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/util/deprecation.py", line 281, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 430, in fit
    loss = self._train_model(input_fn=input_fn, hooks=hooks)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 925, in _train_model
    features, labels = input_fn()
  File "seq2seq/training/utils.py", line 288, in input_fn
    name="batch_queue")
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/input.py", line 919, in batch
    name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/input.py", line 702, in _batch
    shapes = _shapes([tensor_list], shapes, enqueue_many)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/input.py", line 634, in _shapes
    raise ValueError("Cannot infer Tensor's rank: %s" % tl[i])
ValueError: Cannot infer Tensor's rank: Tensor("train_input_fn/parallel_read/common_queue_Dequeue:0", dtype=string)
```

After a bit of digging around I've found that the referenced Tensor ("record_keys") is automatically added by tf.contrib.slim.dataset_data_provider.DatasetDataProvider, so I'm not sure how to go about specifying its rank.

My previous TensorFlow experience involving manually loading data from proprietary binary files, feeding it into a RandomShuffleQueue, and interacting with that directly, so I'm new to the pipeline approach and am having trouble figuring it out.  If anyone could help me figure out where I'm going wrong, it would be greatly appreciated!

**Comment by syed-ahmed** [comment]
Hi @wingsbr. I'm similarly adapting this framework for video captioning and have faced this same error on the "record_keys". From the data provider class, it seems like the "record_key" param is just a reference to the example being dequeued (not really sure about it). Hence, I was thinking if it's just a redundant key. Looking at the ParallelDataProvider call, it doesn't append any "record_key" and hence, I just popped the "record_key" from the features_and_labels map.

**Comment by apcode** [comment]
@syed-ahmed Do you have a sample diff for this change?

**Comment by syed-ahmed** [comment]
Hi @apcode , Here is the change: https://github.com/syed-ahmed/seq2seq/blob/master/seq2seq/training/utils.py#L290. You can just add this line before the `bucket_by_sequence_example`.
