### ISSUE TITLE
Win10: tensorflow.contrib.tfprof has no attribute 'model_analyzer'.

### ISSUE THREAD

**Issue by PAK90** [google/seq2seq#159]
On a Windows 10 system, Python 3.5.2, TF 1.0. Runs two tests, fails the last one with this message:

```
======================================================================
ERROR: test_train_infer (seq2seq.test.pipeline_test.PipelineTest)
Tests training and inference scripts.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\work\Documents\seq2seq\seq2seq\test\pipeline_test.py", line 148, in test_train_infer
    train_script.main([])
  File "C:\Users\work\Documents\seq2seq\bin\train.py", line 271, in main
    schedule=FLAGS.schedule)
  File "C:\Users\work\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\contrib\learn\python\learn\learn_runner.py", line 106, in run
    return task()
  File "C:\Users\work\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\contrib\learn\python\learn\experiment.py", line 459, in train_and_evaluate
    self.train(delay_secs=0)
  File "C:\Users\work\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\contrib\learn\python\learn\experiment.py", line 281, in train
    monitors=self._train_monitors + extra_hooks)
  File "C:\Users\work\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\util\deprecation.py", line 280, in new_func
    return func(*args, **kwargs)
  File "C:\Users\work\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\contrib\learn\python\learn\estimators\estimator.py", line 426, in fit
    loss = self._train_model(input_fn=input_fn, hooks=hooks)
  File "C:\Users\work\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\contrib\learn\python\learn\estimators\estimator.py", line 981, in _train_model
    config=self.config.tf_config) as mon_sess:
  File "C:\Users\work\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\training\monitored_session.py", line 315, in MonitoredTrainingSession
    return MonitoredSession(session_creator=session_creator, hooks=all_hooks)
  File "C:\Users\work\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\training\monitored_session.py", line 601, in __init__
    session_creator, hooks, should_recover=True)
  File "C:\Users\work\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\training\monitored_session.py", line 428, in __init__
    h.begin()
  File "C:\Users\work\Documents\seq2seq\seq2seq\training\hooks.py", line 246, in begin
    opts = tf.contrib.tfprof.model_analyzer.TRAINABLE_VARS_PARAMS_STAT_OPTIONS
AttributeError: module 'tensorflow.contrib.tfprof' has no attribute 'model_analyzer'

----------------------------------------------------------------------
Ran 2 tests in 5.876s

FAILED (errors=1)
```

From what I've seen in [other issues](https://github.com/tensorflow/tensorflow/issues/6791), tf.contrib support is not currently complete for Windows, so I'm guessing that's the problem.

**Comment by wolfshow** [comment]
yes, i have the same problem because tf.contrib is not ready for windows.

**Comment by dennybritz** [comment]
Yep. Sorry, there no windows support for now, until tf.contrib has windows support.

**Comment by soukira** [comment]
I have the same problem , is there windows support for  tf.contrib now
