### ISSUE TITLE
unit test error

### ISSUE THREAD

**Issue by ruiquanhe** [google/seq2seq#160]
on centos Python 2.7, Tensorflow 1.01
when i run the command:python -m unittest seq2seq.test.pipeline_test
there are some errors,like:
![image](https://cloud.githubusercontent.com/assets/27407138/24995154/50d61cd0-2060-11e7-9625-b50bd67cabf2.png)

how can i fix it

**Comment by tschul** [comment]
Same here, Ubuntu 16.04.2 LTS, tf 1.0.1, pip CPU install, every package up-to-date through pip-review.

**Comment by esalesky** [comment]
Same. 
TensorFlow 1.0.1, CUDA 0.8.0, Python 2.7, Ubuntu 14.04
I get the error on both CPU and GPU (slightly different trace). Both state 'Caused by op u'bleu/value' directly after the last line in first poster's screenshot.

**Comment by esalesky** [comment]
solved by getting the multi-bleu file locally (uncommenting seq2seq/seq2seq/metrics/bleu.py 56-58 and commenting 50-53), thanks @SwordYork
urllib.request.urlretrieve is python 3.0 syntax, not 2.7
can stick this section into a try block or just uncomment the one that you need for version of python

**Comment by SwordYork** [comment]
@esalesky Never mind. 
We could use `urllib.request.urlretrieve` syntax because it is imported as `from six.moves import urllib`.
But the urllib of python 2 is not very reliable, thus may be problematic sometimes. 
Use a try block will be better.

**Comment by dennybritz** [comment]
Thanks for reporting. Yeah, I'll put this into a try block and/or use the local file instead.

**Comment by yanghoonkim** [comment]
I have the similar issue at #266 ,, and i also tried to ran ```python -m unittest seq2seq.test.pipeline_test``` I got the similar error. I think it isn't totally solved yet... @dennybritz 
ubuntu 16.04, tensorflow 1.2

```
======================================================================
ERROR: test_train_infer (seq2seq.test.pipeline_test.PipelineTest)
Tests training and inference scripts.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ad26kr/utils/seq2seq/seq2seq/test/pipeline_test.py", line 148, in test_train_infer
    train_script.main([])
  File "/home/ad26kr/utils/seq2seq/bin/train.py", line 272, in main
    schedule=FLAGS.schedule)
  File "/home/ad26kr/miniconda2/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/learn_runner.py", line 210, in run
    return _execute_schedule(experiment, schedule)
  File "/home/ad26kr/miniconda2/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/learn_runner.py", line 47, in _execute_schedule
    return task()
  File "/home/ad26kr/utils/seq2seq/seq2seq/contrib/experiment.py", line 112, in continuous_train_and_eval
    hooks=self._eval_hooks)
  File "/home/ad26kr/miniconda2/lib/python2.7/site-packages/tensorflow/python/util/deprecation.py", line 289, in new_func
    return func(*args, **kwargs)
  File "/home/ad26kr/miniconda2/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 543, in evaluate
    log_progress=log_progress)
  File "/home/ad26kr/miniconda2/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 855, in _evaluate_model
    config=self._session_config)
  File "/home/ad26kr/miniconda2/lib/python2.7/site-packages/tensorflow/python/training/evaluation.py", line 182, in _evaluate_once
    session.run(eval_ops, feed_dict)
  File "/home/ad26kr/miniconda2/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 505, in run
    run_metadata=run_metadata)
  File "/home/ad26kr/miniconda2/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 842, in run
    run_metadata=run_metadata)
  File "/home/ad26kr/miniconda2/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 798, in run
    return self._sess.run(*args, **kwargs)
  File "/home/ad26kr/miniconda2/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 952, in run
    run_metadata=run_metadata)
  File "/home/ad26kr/miniconda2/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 798, in run
    return self._sess.run(*args, **kwargs)
  File "/home/ad26kr/miniconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 789, in run
    run_metadata_ptr)
  File "/home/ad26kr/miniconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 997, in _run
    feed_dict_string, options, run_metadata)
  File "/home/ad26kr/miniconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1132, in _do_run
    target_list, options, run_metadata)
  File "/home/ad26kr/miniconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1152, in _do_call
    raise type(e)(node_def, op, message)
UnknownError: exceptions.OSError: [Errno 8] Exec format error
         [[Node: bleu/value = PyFunc[Tin=[DT_STRING, DT_STRING], Tout=[DT_FLOAT], token="pyfunc_0", _device="/job:localhost/replica:0/task:0/cpu:0"](bleu/Identity, bleu/Identity_1)]]
         [[Node: bleu/value/_299 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_254_bleu/value", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]

Caused by op u'bleu/value', defined at:
  File "/home/ad26kr/miniconda2/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/home/ad26kr/miniconda2/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/ad26kr/miniconda2/lib/python2.7/unittest/__main__.py", line 12, in <module>
    main(module=None)
  File "/home/ad26kr/miniconda2/lib/python2.7/unittest/main.py", line 95, in __init__
    self.runTests()
  File "/home/ad26kr/miniconda2/lib/python2.7/unittest/main.py", line 232, in runTests
    self.result = testRunner.run(self.test)
  File "/home/ad26kr/miniconda2/lib/python2.7/unittest/runner.py", line 151, in run
    test(result)
  File "/home/ad26kr/miniconda2/lib/python2.7/unittest/suite.py", line 70, in __call__
    return self.run(*args, **kwds)
  File "/home/ad26kr/miniconda2/lib/python2.7/unittest/suite.py", line 108, in run
    test(result)
  File "/home/ad26kr/miniconda2/lib/python2.7/unittest/suite.py", line 70, in __call__
    return self.run(*args, **kwds)
  File "/home/ad26kr/miniconda2/lib/python2.7/unittest/suite.py", line 108, in run
    test(result)
  File "/home/ad26kr/miniconda2/lib/python2.7/unittest/suite.py", line 70, in __call__
    return self.run(*args, **kwds)
  File "/home/ad26kr/miniconda2/lib/python2.7/unittest/suite.py", line 108, in run
    test(result)
  File "/home/ad26kr/miniconda2/lib/python2.7/unittest/case.py", line 393, in __call__
    return self.run(*args, **kwds)
  File "/home/ad26kr/miniconda2/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/home/ad26kr/utils/seq2seq/seq2seq/test/pipeline_test.py", line 148, in test_train_infer
    train_script.main([])
  File "/home/ad26kr/utils/seq2seq/bin/train.py", line 272, in main
    schedule=FLAGS.schedule)
  File "/home/ad26kr/miniconda2/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/learn_runner.py", line 210, in run
    return _execute_schedule(experiment, schedule)
  File "/home/ad26kr/miniconda2/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/learn_runner.py", line 47, in _execute_schedule
    return task()
  File "/home/ad26kr/utils/seq2seq/seq2seq/contrib/experiment.py", line 112, in continuous_train_and_eval
    hooks=self._eval_hooks)
  File "/home/ad26kr/miniconda2/lib/python2.7/site-packages/tensorflow/python/util/deprecation.py", line 289, in new_func
    return func(*args, **kwargs)
  File "/home/ad26kr/miniconda2/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 543, in evaluate
    log_progress=log_progress)
  File "/home/ad26kr/miniconda2/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 829, in _evaluate_model
    model_fn_results = self._get_eval_ops(features, labels, metrics)
  File "/home/ad26kr/miniconda2/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 1196, in _get_eval_ops
    metrics, features, labels, model_fn_ops.predictions))
  File "/home/ad26kr/miniconda2/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 269, in _make_metrics_ops
    result[name] = metric.create_metric_ops(features, labels, predictions)
  File "/home/ad26kr/utils/seq2seq/seq2seq/metrics/metric_specs.py", line 124, in create_metric_ops
    name="value")
  File "/home/ad26kr/miniconda2/lib/python2.7/site-packages/tensorflow/python/ops/script_ops.py", line 198, in py_func
    input=inp, token=token, Tout=Tout, name=name)
  File "/home/ad26kr/miniconda2/lib/python2.7/site-packages/tensorflow/python/ops/gen_script_ops.py", line 38, in _py_func
    name=name)
  File "/home/ad26kr/miniconda2/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "/home/ad26kr/miniconda2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2506, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/ad26kr/miniconda2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1269, in __init__
    self._traceback = _extract_stack()

UnknownError (see above for traceback): exceptions.OSError: [Errno 8] Exec format error
         [[Node: bleu/value = PyFunc[Tin=[DT_STRING, DT_STRING], Tout=[DT_FLOAT], token="pyfunc_0", _device="/job:localhost/replica:0/task:0/cpu:0"](bleu/Identity, bleu/Identity_1)]]
         [[Node: bleu/value/_299 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_254_bleu/value", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]


----------------------------------------------------------------------
Ran 2 tests in 23.334s

FAILED (errors=1)

```

**Comment by guangzhixie** [comment]
I encountered a similar issue as @ad26kt . However I did not have the issue when either running the unit test or the toy data example. The issue is encountered during training with a large parallel corpus with nmt_large.yml config.
ubuntu 16.04, tensorflow 1.2
```
Traceback (most recent call last):
  File "/home/frankxgz/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/script_ops.py", line 82, in __call__
    ret = func(*args)
  File "seq2seq/metrics/metric_specs.py", line 156, in _py_func
    return self.metric_fn(sliced_hypotheses, sliced_references) #pylint: disable=E1102
  File "seq2seq/metrics/metric_specs.py", line 181, in metric_fn
    return bleu.moses_multi_bleu(hypotheses, references, lowercase=False)
  File "seq2seq/metrics/bleu.py", line 79, in moses_multi_bleu
    bleu_cmd, stdin=read_pred, stderr=subprocess.STDOUT)
  File "/home/frankxgz/anaconda2/lib/python2.7/subprocess.py", line 212, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/home/frankxgz/anaconda2/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/home/frankxgz/anaconda2/lib/python2.7/subprocess.py", line 1024, in _execute_child
    raise child_exception
OSError: [Errno 8] Exec format error
2017-08-23 11:54:17.528452: W tensorflow/core/framework/op_kernel.cc:1152] Internal: Failed to run py callback pyfunc_0: see error log.
Traceback (most recent call last):
  File "/home/frankxgz/anaconda2/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/home/frankxgz/anaconda2/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/frankxgz/seq2seq/bin/train.py", line 277, in <module>
    tf.app.run()
  File "/home/frankxgz/anaconda2/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/home/frankxgz/seq2seq/bin/train.py", line 272, in main
    schedule=FLAGS.schedule)
  File "/home/frankxgz/anaconda2/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/learn_runner.py", line 111, in run
    return _execute_schedule(experiment, schedule)
  File "/home/frankxgz/anaconda2/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/learn_runner.py", line 46, in _execute_schedule
    return task()
  File "seq2seq/contrib/experiment.py", line 112, in continuous_train_and_eval
    hooks=self._eval_hooks)
  File "/home/frankxgz/anaconda2/lib/python2.7/site-packages/tensorflow/python/util/deprecation.py", line 281, in new_func
    return func(*args, **kwargs)
  File "/home/frankxgz/anaconda2/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 518, in evaluate
    log_progress=log_progress)
  File "/home/frankxgz/anaconda2/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 828, in _evaluate_model
    config=config_pb2.ConfigProto(allow_soft_placement=True))
  File "/home/frankxgz/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/evaluation.py", line 182, in _evaluate_once
    session.run(eval_ops, feed_dict)
  File "/home/frankxgz/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 484, in run
    run_metadata=run_metadata)
  File "/home/frankxgz/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 820, in run
    run_metadata=run_metadata)
  File "/home/frankxgz/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 776, in run
    return self._sess.run(*args, **kwargs)
  File "/home/frankxgz/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 930, in run
    run_metadata=run_metadata)
  File "/home/frankxgz/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 776, in run
    return self._sess.run(*args, **kwargs)
  File "/home/frankxgz/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 778, in run
    run_metadata_ptr)
  File "/home/frankxgz/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 982, in _run
    feed_dict_string, options, run_metadata)
  File "/home/frankxgz/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1032, in _do_run
    target_list, options, run_metadata)
  File "/home/frankxgz/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1052, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InternalError: Failed to run py callback pyfunc_0: see error log.
	 [[Node: bleu/value = PyFunc[Tin=[DT_STRING, DT_STRING], Tout=[DT_FLOAT], token="pyfunc_0", _device="/job:localhost/replica:0/task:0/cpu:0"](bleu/Identity, bleu/Identity_1)]]

Caused by op u'bleu/value', defined at:
  File "/home/frankxgz/anaconda2/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/home/frankxgz/anaconda2/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/frankxgz/seq2seq/bin/train.py", line 277, in <module>
    tf.app.run()
  File "/home/frankxgz/anaconda2/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/home/frankxgz/seq2seq/bin/train.py", line 272, in main
    schedule=FLAGS.schedule)
  File "/home/frankxgz/anaconda2/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/learn_runner.py", line 111, in run
    return _execute_schedule(experiment, schedule)
  File "/home/frankxgz/anaconda2/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/learn_runner.py", line 46, in _execute_schedule
    return task()
  File "seq2seq/contrib/experiment.py", line 112, in continuous_train_and_eval
    hooks=self._eval_hooks)
  File "/home/frankxgz/anaconda2/lib/python2.7/site-packages/tensorflow/python/util/deprecation.py", line 281, in new_func
    return func(*args, **kwargs)
  File "/home/frankxgz/anaconda2/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 518, in evaluate
    log_progress=log_progress)
  File "/home/frankxgz/anaconda2/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 804, in _evaluate_model
    eval_dict = self._get_eval_ops(features, labels, metrics).eval_metric_ops
  File "/home/frankxgz/anaconda2/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 1166, in _get_eval_ops
    metrics, features, labels, model_fn_ops.predictions))
  File "/home/frankxgz/anaconda2/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 257, in _make_metrics_ops
    result[name] = metric.create_metric_ops(features, labels, predictions)
  File "seq2seq/metrics/metric_specs.py", line 124, in create_metric_ops
    name="value")
  File "/home/frankxgz/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/script_ops.py", line 189, in py_func
    input=inp, token=token, Tout=Tout, name=name)
  File "/home/frankxgz/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/gen_script_ops.py", line 40, in _py_func
    name=name)
  File "/home/frankxgz/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 768, in apply_op
    op_def=op_def)
  File "/home/frankxgz/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2336, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/frankxgz/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1228, in __init__
    self._traceback = _extract_stack()

InternalError (see above for traceback): Failed to run py callback pyfunc_0: see error log.
	 [[Node: bleu/value = PyFunc[Tin=[DT_STRING, DT_STRING], Tout=[DT_FLOAT], token="pyfunc_0", _device="/job:localhost/replica:0/task:0/cpu:0"](bleu/Identity, bleu/Identity_1)]]
```

**Comment by xvshiting** [comment]
I encountered the same question,when I ran " python -m unittest seq2seq.test.pipeline_test" 
python 2.7 tensorflow 1.0  macOS sierra
`ERROR: test_train_infer (seq2seq.test.pipeline_test.PipelineTest)
Tests training and inference scripts.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "seq2seq/test/pipeline_test.py", line 148, in test_train_infer
    train_script.main([])
  File "/Users/apple/Desktop/workspace/seq2seq/bin/train.py", line 272, in main
    schedule=FLAGS.schedule)
  File "/Library/Python/2.7/site-packages/tensorflow/contrib/learn/python/learn/learn_runner.py", line 106, in run
    return task()
  File "seq2seq/contrib/experiment.py", line 112, in continuous_train_and_eval
    hooks=self._eval_hooks)
  File "/Library/Python/2.7/site-packages/tensorflow/python/util/deprecation.py", line 280, in new_func
    return func(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 514, in evaluate
    log_progress=log_progress)
  File "/Library/Python/2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 836, in _evaluate_model
    hooks=hooks)
  File "/Library/Python/2.7/site-packages/tensorflow/contrib/training/python/training/evaluation.py", line 430, in evaluate_once
    session.run(eval_ops, feed_dict)
  File "/Library/Python/2.7/site-packages/tensorflow/python/training/monitored_session.py", line 462, in run
    run_metadata=run_metadata)
  File "/Library/Python/2.7/site-packages/tensorflow/python/training/monitored_session.py", line 786, in run
    run_metadata=run_metadata)
  File "/Library/Python/2.7/site-packages/tensorflow/python/training/monitored_session.py", line 744, in run
    return self._sess.run(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/tensorflow/python/training/monitored_session.py", line 891, in run
    run_metadata=run_metadata)
  File "/Library/Python/2.7/site-packages/tensorflow/python/training/monitored_session.py", line 744, in run
    return self._sess.run(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/tensorflow/python/client/session.py", line 767, in run
    run_metadata_ptr)
  File "/Library/Python/2.7/site-packages/tensorflow/python/client/session.py", line 965, in _run
    feed_dict_string, options, run_metadata)
  File "/Library/Python/2.7/site-packages/tensorflow/python/client/session.py", line 1015, in _do_run
    target_list, options, run_metadata)
  File "/Library/Python/2.7/site-packages/tensorflow/python/client/session.py", line 1035, in _do_call
    raise type(e)(node_def, op, message)
InternalError: Failed to run py callback pyfunc_0: see error log.
	 [[Node: bleu/value = PyFunc[Tin=[DT_STRING, DT_STRING], Tout=[DT_FLOAT], token="pyfunc_0", _device="/job:localhost/replica:0/task:0/cpu:0"](bleu/Identity, bleu/Identity_1)]]

Caused by op u'bleu/value', defined at:
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/__main__.py", line 12, in <module>
    main(module=None)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/main.py", line 95, in __init__
    self.runTests()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/main.py", line 232, in runTests
    self.result = testRunner.run(self.test)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/runner.py", line 151, in run
    test(result)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/suite.py", line 70, in __call__
    return self.run(*args, **kwds)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/suite.py", line 108, in run
    test(result)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/suite.py", line 70, in __call__
    return self.run(*args, **kwds)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/suite.py", line 108, in run
    test(result)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/suite.py", line 70, in __call__
    return self.run(*args, **kwds)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/suite.py", line 108, in run
    test(result)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/case.py", line 395, in __call__
    return self.run(*args, **kwds)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/case.py", line 331, in run
    testMethod()
  File "seq2seq/test/pipeline_test.py", line 148, in test_train_infer
    train_script.main([])
  File "/Users/apple/Desktop/workspace/seq2seq/bin/train.py", line 272, in main
    schedule=FLAGS.schedule)
  File "/Library/Python/2.7/site-packages/tensorflow/contrib/learn/python/learn/learn_runner.py", line 106, in run
    return task()
  File "seq2seq/contrib/experiment.py", line 112, in continuous_train_and_eval
    hooks=self._eval_hooks)
  File "/Library/Python/2.7/site-packages/tensorflow/python/util/deprecation.py", line 280, in new_func
    return func(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 514, in evaluate
    log_progress=log_progress)
  File "/Library/Python/2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 810, in _evaluate_model
    eval_ops = self._get_eval_ops(features, labels, metrics)
  File "/Library/Python/2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 1195, in _get_eval_ops
    metrics, features, labels, model_fn_ops.predictions))
  File "/Library/Python/2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 258, in _make_metrics_ops
    result[name] = metric.create_metric_ops(features, labels, predictions)
  File "seq2seq/metrics/metric_specs.py", line 124, in create_metric_ops
    name="value")
  File "/Library/Python/2.7/site-packages/tensorflow/python/ops/script_ops.py", line 192, in py_func
    input=inp, token=token, Tout=Tout, name=name)
  File "/Library/Python/2.7/site-packages/tensorflow/python/ops/gen_script_ops.py", line 40, in _py_func
    name=name)
  File "/Library/Python/2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 763, in apply_op
    op_def=op_def)
  File "/Library/Python/2.7/site-packages/tensorflow/python/framework/ops.py", line 2395, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/Library/Python/2.7/site-packages/tensorflow/python/framework/ops.py", line 1264, in __init__
    self._traceback = _extract_stack()

InternalError (see above for traceback): Failed to run py callback pyfunc_0: see error log.
	 [[Node: bleu/value = PyFunc[Tin=[DT_STRING, DT_STRING], Tout=[DT_FLOAT], token="pyfunc_0", _device="/job:localhost/replica:0/task:0/cpu:0"](bleu/Identity, bleu/Identity_1)]]
`
