### ISSUE TITLE
Unit test issue after installation

### ISSUE THREAD

**Issue by SkyTreasure** [google/seq2seq#164]
After installation when i run this command -
python -m unittest seq2seq.test.pipeline_test 

```
`ERROR: seq2seq (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: seq2seq
Traceback (most recent call last):
  File "/home/akash/anaconda3/envs/tensorflow/lib/python3.5/unittest/loader.py", line 153, in loadTestsFromName
    module = __import__(module_name)
  File "/home/akash/Desktop/Purvo/Learning/DeepLearning/TensorFlow/seq2seq/seq2seq/__init__.py", line 26, in <module>
    from seq2seq import decoders
  File "/home/akash/Desktop/Purvo/Learning/DeepLearning/TensorFlow/seq2seq/seq2seq/decoders/__init__.py", line 17, in <module>
    from seq2seq.decoders.rnn_decoder import *
  File "/home/akash/Desktop/Purvo/Learning/DeepLearning/TensorFlow/seq2seq/seq2seq/decoders/rnn_decoder.py", line 33, in <module>
    from seq2seq.encoders.rnn_encoder import _default_rnn_cell_params
  File "/home/akash/Desktop/Purvo/Learning/DeepLearning/TensorFlow/seq2seq/seq2seq/encoders/__init__.py", line 17, in <module>
    import seq2seq.encoders.rnn_encoder
  File "/home/akash/Desktop/Purvo/Learning/DeepLearning/TensorFlow/seq2seq/seq2seq/encoders/rnn_encoder.py", line 24, in <module>
    from tensorflow.contrib.rnn.python.ops import rnn
  File "/home/akash/anaconda3/envs/tensorflow/lib/python3.5/site-packages/tensorflow/contrib/rnn/python/ops/rnn.py", line 20, in <module>
    from tensorflow.contrib.rnn.python.ops import core_rnn as contrib_rnn
  File "/home/akash/anaconda3/envs/tensorflow/lib/python3.5/site-packages/tensorflow/contrib/rnn/python/ops/core_rnn.py", line 22, in <module>
    from tensorflow.contrib.rnn.python.ops import core_rnn_cell
  File "/home/akash/anaconda3/envs/tensorflow/lib/python3.5/site-packages/tensorflow/contrib/rnn/python/ops/core_rnn_cell.py", line 49, in <module>
    from tensorflow.python.util.all_util import remove_undocumented
ImportError: cannot import name 'remove_undocumented'


----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (errors=1)
`
```

**Comment by dennybritz** [comment]
Which Tensorflow version is this?

**Comment by SkyTreasure** [comment]
0.10.0rc0

**Comment by dennybritz** [comment]
I see. Please upgrade to 1.0. This code only supports > 1.0.
