### ISSUE TITLE
KeyError: 'attention_scores' when setting unk_replace to True

### ISSUE THREAD

**Issue by pnpnpn** [google/seq2seq#174]
I am getting the following error when I ran decoding with `unk_replace`. The training was done with `nmt_medium.yml`, which is using `AttentionSeq2Seq` model. 

```
Traceback (most recent call last):
  File "/Users/png/.pyenv/versions/3.5.3/lib/python3.5/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/png/.pyenv/versions/3.5.3/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/png/repos/seq2seq/bin/infer.py", line 129, in <module>
    tf.app.run()
  File "/Users/png/.pyenv/versions/tf-seq2seq/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/Users/png/repos/seq2seq/bin/infer.py", line 125, in main
    sess.run([])
  File "/Users/png/.pyenv/versions/tf-seq2seq/lib/python3.5/site-packages/tensorflow/python/training/monitored_session.py", line 462, in run
    run_metadata=run_metadata)
  File "/Users/png/.pyenv/versions/tf-seq2seq/lib/python3.5/site-packages/tensorflow/python/training/monitored_session.py", line 786, in run
    run_metadata=run_metadata)
  File "/Users/png/.pyenv/versions/tf-seq2seq/lib/python3.5/site-packages/tensorflow/python/training/monitored_session.py", line 744, in run
    return self._sess.run(*args, **kwargs)
  File "/Users/png/.pyenv/versions/tf-seq2seq/lib/python3.5/site-packages/tensorflow/python/training/monitored_session.py", line 899, in run
    run_metadata=run_metadata))
  File "/Users/png/repos/seq2seq/seq2seq/tasks/decode_text.py", line 172, in after_run
    attention_scores = fetches["attention_scores"]
KeyError: 'attention_scores'
```

**Comment by liming-vie** [comment]
I have the same error here...I wonder if you have solved it?

**Comment by shonosuke** [comment]
I had the same error.
I found that it occurs only when I use both `unk_replace` and `inference.beam_search`.
The error does not occur when only one of them is used.

**Comment by vijaydaultani** [comment]
I think in the current version of the implementation it is not possible to use both unk_replace and beam_search together, because either you can specify either **AttentionDecoder** or **BeamSearchDecoder** but not both at the same time. I will be more than happy to extend the idea of using unk_replace for the beam search. In fact I have a use case where I want to use unk_replace for top k beams of the beam search. But before moving with the implementation I would like to get some suggestions ( @dennybritz ) what would be the best way to implement the same, considering the current project and its modules.

**Comment by vijaydaultani** [comment]
It seems like my previous understanding was not correct and actually **BeamSearchDecoder** wraps around the **AttentionDecoder** in case if we use latter during training our model. Since step function of BeamSearchDecoder first calls step function of the original decoder (Attention Decoder) (Calculate the attention scores) and then perform the step of the beam search (i.e. beam_search_step function). Still I could not figure out the reason why attention_scores gives keyError. Someone trying to work on this issue had any luck of solving it? @dennybritz can you help us with the direction of looking into.

**Comment by Blockost** [comment]
I will be more than interested if someone comes up with an idea to try this out :+1:

**Comment by nevakanezzar** [comment]
I too discovered this behaviour today. I'll look into it as best I can, but it would be cool if we can get perspectives from the devs on this

**Comment by vijaydaultani** [comment]
Well I was able to make it work, i.e. beam search with attention scores.

Changes I made, in hook of dump_beams, before_run function I asked to fetch attention_scores along with source_tokens information. And in after_run function I dumped it along with other previous information of dump_beams. Then I wrote another python script namely generate_beam_attention_viz.py. In this script I basically merged the functionalities of dump_attention and generate_beam_viz together and then used matplotlib to visualize beam vs source_tokens for all beams in beam search.

I am not sure the way I worked out it is the cleanest way (especially when I am merging the functionalities of both generate_beam_viz and dump_attention) but it works for my usecase.

**Comment by nevakanezzar** [comment]
I'm not sure I see how this relates to combining the copy-mechanism (unk_replace: True) and the beam search decoder.

**Comment by vijaydaultani** [comment]
@nevakanezzar Basically I explored all the beams using the tree structure of [beam_search](https://google.github.io/seq2seq/tools/#visualizing-beam-search) and then I replaced each UNK token in the beam using corresponding attention_scores which is of size = len(source_tokens). You can have a look into dump_attention code as a reference. In dump_attention it considers only one beam where as in my script I considered it for all the beams.

**Comment by Blockost** [comment]
@vijaydaultani When I try to fetch attention_scores `fetches["attention_scores"] = self._predictions["attention_scores"]` in before_run function, I get the `KeyError: u'attention_scores'`. How did you pass the attention_scores through it ? 

**EDIT**: I used `self._predictions["beam_search_output.original_outputs.attention_scores"]` instead. Is that what you did ?
