### ISSUE TITLE
Error when running sample unittest

### ISSUE THREAD

**Issue by sidoki** [google/seq2seq#220]
Hi guys,

i'm experiencing error when running sample unittest provided in seq2seq setup (https://google.github.io/seq2seq/getting_started/)

> Traceback (most recent call last):
  File "/opt/anaconda2/envs/ds-env/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/opt/anaconda2/envs/ds-env/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/opt/anaconda2/envs/ds-env/lib/python2.7/unittest/__main__.py", line 12, in <module>
    main(module=None)
  File "/opt/anaconda2/envs/ds-env/lib/python2.7/unittest/main.py", line 94, in __init__
    self.parseArgs(argv)
  File "/opt/anaconda2/envs/ds-env/lib/python2.7/unittest/main.py", line 149, in parseArgs
    self.createTests()
  File "/opt/anaconda2/envs/ds-env/lib/python2.7/unittest/main.py", line 158, in createTests
    self.module)
  File "/opt/anaconda2/envs/ds-env/lib/python2.7/unittest/loader.py", line 130, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/opt/anaconda2/envs/ds-env/lib/python2.7/unittest/loader.py", line 91, in loadTestsFromName
    module = __import__('.'.join(parts_copy))
  File "seq2seq/__init__.py", line 24, in <module>
    from seq2seq import contrib
ImportError: cannot import name contrib

Anyone know how to solve this? Thank you!

**Comment by Zeco-01** [comment]
Are you using tensorflow 1.1.0? I think this is because there are some changes in tf from 1.0 to 1.1 I have run this with tf1.0 and everything is ok.

**Comment by sidoki** [comment]
hi @Zeco-01,

Yeah, i just realized that it works for version 1 and upper. thanks by the way!
