### ISSUE TITLE
Regex issue while going through NMT tutorial on python 3.4

### ISSUE THREAD

**Issue by tareksakakini** [google/seq2seq#243]
Hello everyone,

I'm going through the [NMT tutorial](https://google.github.io/seq2seq/nmt/#neural-machine-translation-background) and I couldn't solve the following error. I was able to go successfully through all of the tutorial on the toy data on python2.7 and on a single CPU. But on python3.4 and on tensorflow with gpu support, when I run the following command:

`python -m bin.train \
  --config_paths="
      ./example_configs/nmt_small.yml,
      ./example_configs/train_seq2seq.yml,
      ./example_configs/text_metrics_bpe.yml" \
  --model_params "
      vocab_source: $VOCAB_SOURCE
      vocab_target: $VOCAB_TARGET" \
  --input_pipeline_train "
    class: ParallelTextInputPipeline
    params:
      source_files:
        - $TRAIN_SOURCES
      target_files:
        - $TRAIN_TARGETS" \
  --input_pipeline_dev "
    class: ParallelTextInputPipeline
    params:
       source_files:
        - $DEV_SOURCES
       target_files:
        - $DEV_TARGETS" \
  --batch_size 32 \
  --train_steps $TRAIN_STEPS \
  --output_dir $MODEL_DIR`

I'm getting the following error (with its traceback):

Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/sakakini/QGen/seq2seq_tutorial/seq2seq/bin/train.py", line 27, in <module>
    import yaml
  File "/home/sakakini/my_python3_pkgs/yaml/__init__.py", line 8, in <module>
    from .loader import *
  File "/home/sakakini/my_python3_pkgs/yaml/loader.py", line 4, in <module>
    from .reader import *
  File "/home/sakakini/my_python3_pkgs/yaml/reader.py", line 45, in <module>
    class Reader(object):
  File "/home/sakakini/my_python3_pkgs/yaml/reader.py", line 137, in Reader
    NON_PRINTABLE = re.compile('[^\x09\x0A\x0D\x20-\x7E\x85\xA0-\uD7FF\uE000-\uFFFD]')
  File "/usr/lib64/python2.7/re.py", line 190, in compile
    return _compile(pattern, flags)
  File "/usr/lib64/python2.7/re.py", line 242, in _compile
    raise error, v # invalid expression
sre_constants.error: bad character range

My tensorflow version is: v1.0.0-65-g4763edf-dirty 1.0.1

Your help is much appreciated, Thanks!

**Comment by tareksakakini** [comment]
Turns out I should have been calling python3.
