### ISSUE TITLE
ImportError: cannot import name contrib

### ISSUE THREAD

**Issue by NajeebTyson** [google/seq2seq#308]
while running the pipeline unit test, i get this error

`Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/lib/python2.7/unittest/__main__.py", line 12, in <module>
    main(module=None)
  File "/usr/lib/python2.7/unittest/main.py", line 94, in __init__
    self.parseArgs(argv)
  File "/usr/lib/python2.7/unittest/main.py", line 149, in parseArgs
    self.createTests()
  File "/usr/lib/python2.7/unittest/main.py", line 158, in createTests
    self.module)
  File "/usr/lib/python2.7/unittest/loader.py", line 130, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/usr/lib/python2.7/unittest/loader.py", line 91, in loadTestsFromName
    module = __import__('.'.join(parts_copy))
  File "seq2seq/__init__.py", line 24, in <module>
    from seq2seq import contrib
ImportError: cannot import name contrib
`

**Comment by knightmarehs** [comment]
Hi, could you tell me how you solved this error?

**Comment by NajeebTyson** [comment]
the problem is basically with the path. it worked for me when i change the path in the code

**Comment by sachinpuranik99** [comment]
I was able to fix the issue by following a comment mentioned in this thread.
https://github.com/google/seq2seq/issues/37

> #from tensorflow.contrib.distributions.python.ops import bernoulli
#from tensorflow.contrib.distributions.python.ops import categorical
try:
    from tensorflow.python.ops.distributions import bernoulli
    from tensorflow.python.ops.distributions import categorical
except:
    from tensorflow.contrib.distributions.python.ops import bernoulli
    from tensorflow.contrib.distributions.python.ops import categorical

In file seq2seq/seq2seq/contrib/seq2seq/helper.py

**Comment by ericp96** [comment]
Worked for me!

**Comment by WwwRuiOP** [comment]
Worked for me!

**Comment by kingofqing** [comment]
It works.
