### ISSUE TITLE
seq2seq model training error importing libraries using tensorflow gpu package

### ISSUE THREAD

**Issue by sahertariq07** [google/seq2seq#351]
System information

    OS Platform: Linux Ubuntu 15.10
    TensorFlow installed from (source or binary):
    TensorFlow version: TensorFlow-GPU 1.0.1
    Python version: 3.7
    Installed using pip command: pip install tensorflow-gpu==1.0.1
    Using anaconda jupyter for programming
    CUDA/cuDNN version: 8
    GPU model and memory:NVIDIA Corporation GM204 [GeForce GTX 970]

I'm using tensorflow-gpu package to train seq2seq model on a dataset. But it gives error during importing libraries.

Traceback (most recent call last):
File "/home/comsats/yes/envs/my-rdkit-env/lib/python3.6/site-packages/tensorflow/python/init.py", line 61, in
from tensorflow.python import pywrap_tensorflow
File "/home/comsats/yes/envs/my-rdkit-env/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 28, in
_pywrap_tensorflow = swig_import_helper()
File "/home/comsats/yes/envs/my-rdkit-env/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 24, in swig_import_helper
_mod = imp.load_module('_pywrap_tensorflow', fp, pathname, description)
File "/home/comsats/yes/envs/my-rdkit-env/lib/python3.6/imp.py", line 243, in load_module
return load_dynamic(name, filename, file)
File "/home/comsats/yes/envs/my-rdkit-env/lib/python3.6/imp.py", line 343, in load_dynamic
return _load(spec)
ImportError: libcudart.so.8.0: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/home/comsats/yes/envs/my-rdkit-env/lib/python3.6/runpy.py", line 193, in _run_module_as_main
"main", mod_spec)
File "/home/comsats/yes/envs/my-rdkit-env/lib/python3.6/runpy.py", line 85, in _run_code
exec(code, run_globals)
File "/home/comsats/Desktop/saher_tariq/Panday_group/reaction_prediction_seq2seq-master/bin/train.py", line 29, in
import tensorflow as tf
File "/home/comsats/yes/envs/my-rdkit-env/lib/python3.6/site-packages/tensorflow/init.py", line 24, in
from tensorflow.python import *
File "/home/comsats/yes/envs/my-rdkit-env/lib/python3.6/site-packages/tensorflow/python/init.py", line 72, in
raise ImportError(msg)
ImportError: Traceback (most recent call last):
File "/home/comsats/yes/envs/my-rdkit-env/lib/python3.6/site-packages/tensorflow/python/init.py", line 61, in
from tensorflow.python import pywrap_tensorflow
File "/home/comsats/yes/envs/my-rdkit-env/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 28, in
_pywrap_tensorflow = swig_import_helper()
File "/home/comsats/yes/envs/my-rdkit-env/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 24, in swig_import_helper
_mod = imp.load_module('_pywrap_tensorflow', fp, pathname, description)
File "/home/comsats/yes/envs/my-rdkit-env/lib/python3.6/imp.py", line 243, in load_module
return load_dynamic(name, filename, file)
File "/home/comsats/yes/envs/my-rdkit-env/lib/python3.6/imp.py", line 343, in load_dynamic
return _load(spec)
ImportError: libcudart.so.8.0: cannot open shared object file: No such file or directory

Failed to load the native TensorFlow runtime.

See https://github.com/tensorflow/tensorflow/blob/master/tensorflow/g3doc/get_started/os_setup.md#import_error
for some common reasons and solutions. Include the entire stack trace
above this error message when asking for help.

I have tried after re-installation of tensorflow but it gives same error. Model works fine when i had used only tensorflow 1.0.1 only for cpu March issue, but was very slow in working. So then i tried for tensorflow-gpu which gives me error mentioned above. 
Any help relating to issue is appreciated.

**Comment by sahertariq07** [comment]
Issue is resolved. See https://github.com/tensorflow/tensorflow/issues/25581
