### ISSUE TITLE
Error while running python -m unittest seq2seq.test.pipeline_test

### ISSUE THREAD

**Issue by andymogul** [google/seq2seq#68]
Hi I'm using Windows 10 and Python 3.5
I got an error message        ImportError: cannot import name 'SecondOrStepTimer'
Can I get some help?

This is the entire error message.
======================================================================
ERROR: seq2seq (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: seq2seq
Traceback (most recent call last):
  File "C:\Users\Bumho\Anaconda3\lib\unittest\loader.py", line 153, in loadTestsFromName
    module = __import__(module_name)
  File "C:\Users\Bumho\seq2seq\seq2seq\__init__.py", line 26, in <module>
    from seq2seq import decoders
  File "C:\Users\Bumho\seq2seq\seq2seq\decoders\__init__.py", line 17, in <module>
    from seq2seq.decoders.rnn_decoder import *
  File "C:\Users\Bumho\seq2seq\seq2seq\decoders\rnn_decoder.py", line 32, in <module>
    from seq2seq.encoders.rnn_encoder import _default_rnn_cell_params
  File "C:\Users\Bumho\seq2seq\seq2seq\encoders\__init__.py", line 17, in <module>
    import seq2seq.encoders.rnn_encoder
  File "C:\Users\Bumho\seq2seq\seq2seq\encoders\rnn_encoder.py", line 27, in <module>
    from seq2seq.training import utils as training_utils
  File "C:\Users\Bumho\seq2seq\seq2seq\training\__init__.py", line 17, in <module>
    from seq2seq.training import hooks
  File "C:\Users\Bumho\seq2seq\seq2seq\training\hooks.py", line 28, in <module>
    from tensorflow.python.training.basic_session_run_hooks import SecondOrStepTimer  # pylint: disable=E0611
ImportError: cannot import name 'SecondOrStepTimer'

**Comment by inoryy** [comment]
For anyone running into the same issue, likely cause is outdated `tensorflow`.
