### ISSUE TITLE
nvalidArgumentError (see above for traceback): Tried to read from index 32 but array size is: 32

### ISSUE THREAD

**Issue by mouna99** [google/seq2seq#69]
Parsing GraphDef...
Parsing RunMetadata...
Parsing OpLog...
Preparing Views...
Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/disk1/mouna/code/seq2seq/bin/train.py", line 251, in <module>
    tf.app.run()
  File "/usr/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/disk1/mouna/code/seq2seq/bin/train.py", line 246, in main
    schedule=FLAGS.schedule)
  File "/usr/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/learn_runner.py", line 106, in run
    return task()
  File "/usr/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/experiment.py", line 459, in train_and_evaluate
    self.train(delay_secs=0)
  File "/usr/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/experiment.py", line 281, in train
    monitors=self._train_monitors + extra_hooks)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/util/deprecation.py", line 280, in new_func
    return func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 426, in fit
    loss = self._train_model(input_fn=input_fn, hooks=hooks)
  File "/usr/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 984, in _train_model
    _, loss = mon_sess.run([model_fn_ops.train_op, model_fn_ops.loss])
  File "/usr/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 462, in run
    run_metadata=run_metadata)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 786, in run
    run_metadata=run_metadata)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 744, in run
    return self._sess.run(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 899, in run
    run_metadata=run_metadata))
  File "/usr/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/monitors.py", line 1157, in after_run
    induce_stop = m.step_end(self._last_step, result)
  File "/usr/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/monitors.py", line 356, in step_end
    return self.every_n_step_end(step, output)
  File "/usr/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/monitors.py", line 657, in every_n_step_end
    steps=self.eval_steps, metrics=self.metrics, name=self.name)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/util/deprecation.py", line 280, in new_func
    return func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 514, in evaluate
    log_progress=log_progress)
  File "/usr/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 836, in _evaluate_model
    hooks=hooks)
  File "/usr/lib/python2.7/site-packages/tensorflow/contrib/training/python/training/evaluation.py", line 430, in evaluate_once
    session.run(eval_ops, feed_dict)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 462, in run
    run_metadata=run_metadata)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 786, in run
    run_metadata=run_metadata)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 744, in run
    return self._sess.run(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 891, in run
    run_metadata=run_metadata)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 744, in run
    return self._sess.run(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 767, in run
    run_metadata_ptr)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 965, in _run
    feed_dict_string, options, run_metadata)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1015, in _do_run
    target_list, options, run_metadata)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1035, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Tried to read from index 32 but array size is: 32
	 [[Node: model/att_seq2seq/decode/attention_decoder_1/decoder/while/CustomHelperNextInputs/TrainingHelperNextInputs/cond/TensorArrayReadV3 = TensorArrayReadV3[_class=["loc:@model/att_seq2seq/decode/TrainingHelper/TensorArray"], dtype=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"](model/att_seq2seq/decode/attention_decoder_1/decoder/while/CustomHelperNextInputs/TrainingHelperNextInputs/cond/TensorArrayReadV3/Switch, model/att_seq2seq/decode/attention_decoder_1/decoder/while/CustomHelperNextInputs/TrainingHelperNextInputs/cond/TensorArrayReadV3/Switch_1/_463, model/att_seq2seq/decode/attention_decoder_1/decoder/while/CustomHelperNextInputs/TrainingHelperNextInputs/cond/TensorArrayReadV3/Switch_2)]]

Caused by op u'model/att_seq2seq/decode/attention_decoder_1/decoder/while/CustomHelperNextInputs/TrainingHelperNextInputs/cond/TensorArrayReadV3', defined at:
  File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/disk1/mouna/code/seq2seq/bin/train.py", line 251, in <module>
    tf.app.run()
  File "/usr/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/disk1/mouna/code/seq2seq/bin/train.py", line 246, in main
    schedule=FLAGS.schedule)
  File "/usr/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/learn_runner.py", line 106, in run
    return task()
  File "/usr/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/experiment.py", line 459, in train_and_evaluate
    self.train(delay_secs=0)
  File "/usr/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/experiment.py", line 281, in train
    monitors=self._train_monitors + extra_hooks)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/util/deprecation.py", line 280, in new_func
    return func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 426, in fit
    loss = self._train_model(input_fn=input_fn, hooks=hooks)
  File "/usr/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 984, in _train_model
    _, loss = mon_sess.run([model_fn_ops.train_op, model_fn_ops.loss])
  File "/usr/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 462, in run
    run_metadata=run_metadata)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 786, in run
    run_metadata=run_metadata)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 744, in run
    return self._sess.run(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 899, in run
    run_metadata=run_metadata))
  File "/usr/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/monitors.py", line 1157, in after_run
    induce_stop = m.step_end(self._last_step, result)
  File "/usr/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/monitors.py", line 356, in step_end
    return self.every_n_step_end(step, output)
  File "/usr/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/monitors.py", line 657, in every_n_step_end
    steps=self.eval_steps, metrics=self.metrics, name=self.name)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/util/deprecation.py", line 280, in new_func
    return func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 514, in evaluate
    log_progress=log_progress)
  File "/usr/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 810, in _evaluate_model
    eval_ops = self._get_eval_ops(features, labels, metrics)
  File "/usr/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 1190, in _get_eval_ops
    features, labels, model_fn_lib.ModeKeys.EVAL)
  File "/usr/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 1133, in _call_model_fn
    model_fn_results = self._model_fn(features, labels, **kwargs)
  File "/disk1/mouna/code/seq2seq/bin/train.py", line 164, in model_fn
    return model(features, labels, params)
  File "seq2seq/models/model_base.py", line 111, in __call__
    return self._build(features, labels, params)
  File "seq2seq/models/seq2seq_model.py", line 263, in _build
    decoder_output, _, = self.decode(encoder_output, features, labels)
  File "seq2seq/graph_utils.py", line 38, in func_wrapper
    return templated_func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/ops/template.py", line 276, in __call__
    return self._call_func(args, kwargs, check_for_new_variables=False)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/ops/template.py", line 216, in _call_func
    result = self._func(*args, **kwargs)
  File "seq2seq/models/basic_seq2seq.py", line 124, in decode
    labels)
  File "seq2seq/models/basic_seq2seq.py", line 87, in _decode_train
    return decoder(decoder_initial_state, helper_train)
  File "seq2seq/graph_module.py", line 57, in __call__
    return self._template(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/ops/template.py", line 267, in __call__
    return self._call_func(args, kwargs, check_for_new_variables=False)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/ops/template.py", line 216, in _call_func
    result = self._func(*args, **kwargs)
  File "seq2seq/decoders/rnn_decoder.py", line 110, in _build
    maximum_iterations=maximum_iterations)
  File "seq2seq/contrib/seq2seq/decoder.py", line 282, in dynamic_decode
    swap_memory=swap_memory)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2605, in while_loop
    result = context.BuildLoop(cond, body, loop_vars, shape_invariants)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2438, in BuildLoop
    pred, body, original_loop_vars, loop_vars, shape_invariants)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2388, in _BuildLoop
    body_result = body(*packed_vars_for_body)
  File "seq2seq/contrib/seq2seq/decoder.py", line 242, in body
    decoder_finished) = decoder.step(time, inputs, state)
  File "seq2seq/decoders/attention_decoder.py", line 186, in step
    time=time_, outputs=outputs, state=cell_state, sample_ids=sample_ids)
  File "seq2seq/contrib/seq2seq/helper.py", line 125, in next_inputs
    time=time, outputs=outputs, state=state, sample_ids=sample_ids)
  File "seq2seq/decoders/attention_decoder.py", line 154, in att_next_inputs
    name=name)
  File "seq2seq/contrib/seq2seq/helper.py", line 204, in next_inputs
    lambda: nest.map_structure(read_from_ta, self._input_tas))
  File "/usr/lib/python2.7/site-packages/tensorflow/python/ops/control_flow_ops.py", line 1745, in cond
    _, res_f = context_f.BuildCondBranch(fn2)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/ops/control_flow_ops.py", line 1639, in BuildCondBranch
    r = fn()
  File "seq2seq/contrib/seq2seq/helper.py", line 204, in <lambda>
    lambda: nest.map_structure(read_from_ta, self._input_tas))
  File "/usr/lib/python2.7/site-packages/tensorflow/python/util/nest.py", line 302, in map_structure
    structure[0], [func(*x) for x in entries])
  File "seq2seq/contrib/seq2seq/helper.py", line 200, in read_from_ta
    return inp.read(next_time)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/ops/tensor_array_ops.py", line 250, in read
    name=name)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/ops/gen_data_flow_ops.py", line 2421, in _tensor_array_read_v3
    name=name)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 763, in apply_op
    op_def=op_def)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2327, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1226, in __init__
    self._traceback = _extract_stack()

InvalidArgumentError (see above for traceback): Tried to read from index 32 but array size is: 32
	 [[Node: model/att_seq2seq/decode/attention_decoder_1/decoder/while/CustomHelperNextInputs/TrainingHelperNextInputs/cond/TensorArrayReadV3 = TensorArrayReadV3[_class=["loc:@model/att_seq2seq/decode/TrainingHelper/TensorArray"], dtype=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"](model/att_seq2seq/decode/attention_decoder_1/decoder/while/CustomHelperNextInputs/TrainingHelperNextInputs/cond/TensorArrayReadV3/Switch, model/att_seq2seq/decode/attention_decoder_1/decoder/while/CustomHelperNextInputs/TrainingHelperNextInputs/cond/TensorArrayReadV3/Switch_1/_463, model/att_seq2seq/decode/attention_decoder_1/decoder/while/CustomHelperNextInputs/TrainingHelperNextInputs/cond/TensorArrayReadV3/Switch_2)]]

**Comment by dennybritz** [comment]
I am not sure. I have seen errors like this happen when using the same GPU in multiple processes. Make sure that you don't have any other python/tensorflow processes running (including notebooks)>

**Comment by ZhangShiyue** [comment]
Thanks for reply my #98 issue. But, actually, I don't have any other processes running. But I run only on one GPU, and encounter this problem at evaluation. Is there any conflict between training and validation?

**Comment by ZhangShiyue** [comment]
I checked the log. It seems when doing validation, a new process is started and trying to use the same GPU and then failed in this error.  It's just my guess. I'm still not quite familiar with the code.

**Comment by dennybritz** [comment]
It's normal that validation loads the model graph again, and it shouldn't be an issue. Otherwise there is no difference between validation and training, except for the data. It's difficult for me to debug this without having a way to reproduce the error..

**Comment by ZhangShiyue** [comment]
Ok, I see. Thank you! But I think this error must be related to GPU, I didn't encounter the problem on CPU. I cannot figure out what's wrong here now. So, I decide to train model only without validation and save more checkpoints to validate later.

**Comment by dennybritz** [comment]
What GPU do you have?

**Comment by ZhangShiyue** [comment]
01:00.0 VGA compatible controller: NVIDIA Corporation GP104 [GeForce GTX 1070] (rev a1)
This GPU works well before, and if I drop the validation and only train, it also works well. So, maybe there are some configs that I ignore or set wrong...

**Comment by manene** [comment]
I met the same error...

**Comment by rihardsk** [comment]
I have also encountered the same error.

**Comment by rihardsk** [comment]
It seems that I might have managed to solve the issue by switching to the latest development version of `Tensorflow` (compiled from source from the `master` branch). At least now I'm getting a different error. See #102. I am not yet sure if now #102 doesn't just make it crash earlier. I will report back if that's the case.

**Comment by dennybritz** [comment]
Thanks for reporting, I do believe all of these issues are caused by the same problem, so I will close them and create a new issue to handle these: https://github.com/google/seq2seq/issues/103

**Comment by akanyaani** [comment]
Hi I am also getting a similar error while training autoencoder.

Caused by op u'decoder/decoder/while/BasicDecoderStep/TrainingHelperNextInputs/cond/TensorArrayReadV3', defined at:
  File "train_autoencoder.py", line 137, in <module>
    tf.app.run()
  File "/home/abhay/anaconda2/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "train_autoencoder.py", line 133, in main
    train_autoencoder()
  File "train_autoencoder.py", line 36, in train_autoencoder
    model = Autoencoder(FLAGS.lstm_units, embedding_matrix, 0, 1, num_layers=FLAGS.num_layers, train_embeddings=False)
  File "/home/abhay/Search_And_Match/encoder.py", line 110, in __init__
    impute_finished=False)
  File "/home/abhay/anaconda2/lib/python2.7/site-packages/tensorflow/contrib/seq2seq/python/ops/decoder.py", line 304, in dynamic_decode
    swap_memory=swap_memory)
  File "/home/abhay/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/control_flow_ops.py", line 3224, in while_loop
    result = loop_context.BuildLoop(cond, body, loop_vars, shape_invariants)
  File "/home/abhay/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2956, in BuildLoop
    pred, body, original_loop_vars, loop_vars, shape_invariants)
  File "/home/abhay/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2893, in _BuildLoop
    body_result = body(*packed_vars_for_body)
  File "/home/abhay/anaconda2/lib/python2.7/site-packages/tensorflow/contrib/seq2seq/python/ops/decoder.py", line 249, in body
    decoder_finished) = decoder.step(time, inputs, state)
  File "/home/abhay/anaconda2/lib/python2.7/site-packages/tensorflow/contrib/seq2seq/python/ops/basic_decoder.py", line 146, in step
    sample_ids=sample_ids)
  File "/home/abhay/anaconda2/lib/python2.7/site-packages/tensorflow/contrib/seq2seq/python/ops/helper.py", line 250, in next_inputs
    lambda: nest.map_structure(read_from_ta, self._input_tas))
  File "/home/abhay/anaconda2/lib/python2.7/site-packages/tensorflow/python/util/deprecation.py", line 432, in new_func
    return func(*args, **kwargs)
  File "/home/abhay/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2072, in cond
    orig_res_f, res_f = context_f.BuildCondBranch(false_fn)
  File "/home/abhay/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/control_flow_ops.py", line 1913, in BuildCondBranch
    original_result = fn()
  File "/home/abhay/anaconda2/lib/python2.7/site-packages/tensorflow/contrib/seq2seq/python/ops/helper.py", line 250, in <lambda>
    lambda: nest.map_structure(read_from_ta, self._input_tas))
  File "/home/abhay/anaconda2/lib/python2.7/site-packages/tensorflow/python/util/nest.py", line 375, in map_structure
    structure[0], [func(*x) for x in entries])
  File "/home/abhay/anaconda2/lib/python2.7/site-packages/tensorflow/contrib/seq2seq/python/ops/helper.py", line 247, in read_from_ta
    return inp.read(next_time)
  File "/home/abhay/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/tensor_array_ops.py", line 861, in read
    return self._implementation.read(index, name=name)
  File "/home/abhay/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/tensor_array_ops.py", line 260, in read
    name=name)
  File "/home/abhay/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/gen_data_flow_ops.py", line 6428, in tensor_array_read_v3
    dtype=dtype, name=name)
  File "/home/abhay/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/abhay/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 3392, in create_op
    op_def=op_def)
  File "/home/abhay/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1718, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): Tried to read from index 50 but array size is: 50
	 [[Node: decoder/decoder/while/BasicDecoderStep/TrainingHelperNextInputs/cond/TensorArrayReadV3 = TensorArrayReadV3[dtype=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](decoder/decoder/while/BasicDecoderStep/TrainingHelperNextInputs/cond/TensorArrayReadV3/Switch, decoder/decoder/while/BasicDecoderStep/TrainingHelperNextInputs/cond/TensorArrayReadV3/Switch_1/_65, decoder/decoder/while/BasicDecoderStep/TrainingHelperNextInputs/cond/TensorArrayReadV3/Switch_2/_67)]]

**Comment by TanyaChowdhury** [comment]
Hey @akanyaani ! I'm getting a very similar stack trace. Please could you tell what you did to solve the error?
