### ISSUE TITLE
run pipeline_test.py

### ISSUE THREAD

**Issue by gdyxml2000** [google/seq2seq#71]
I have install seq2seq sucessfully in window 10 with tensorflow-gpu (1.0)
when I run the seq2seq.test.pipeline_test.py 
it Prompt errors:

Traceback (most recent call last):
  File "F:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\ops\script_ops.py", line 85, in __call__
    ret = func(*args)
  File "H:\java_pro\tensorflow\project_src\seq2seq-master\seq2seq-master\seq2seq\metrics\metric_specs.py", line 132, in _py_func
    return self.metric_fn(sliced_hypotheses, sliced_references)
  File "H:\java_pro\tensorflow\project_src\seq2seq-master\seq2seq-master\seq2seq\metrics\metric_specs.py", line 157, in metric_fn
    return bleu.moses_multi_bleu(hypotheses, references, lowercase=False)
  File "H:\java_pro\tensorflow\project_src\seq2seq-master\seq2seq-master\seq2seq\metrics\bleu.py", line 71, in moses_multi_bleu
    with open(hypothesis_file.name, "r") as read_pred:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\gdy\\AppData\\Local\\Temp\\tmpjo9ekggj'
W c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\framework\op_kernel.cc:993] Internal: Failed to run py callback pyfunc_0: see error log.
EF:\Program Files\Anaconda3\lib\unittest\case.py:628: ResourceWarning: unclosed file <_io.BufferedRandom name=3>
  outcome.errors.clear()
F:\Program Files\Anaconda3\lib\unittest\case.py:628: ResourceWarning: unclosed file <_io.BufferedRandom name=4>
  outcome.errors.clear()
F:\Program Files\Anaconda3\lib\unittest\case.py:628: ResourceWarning: unclosed file <_io.BufferedRandom name=5>
  outcome.errors.clear()
F:\Program Files\Anaconda3\lib\unittest\case.py:628: ResourceWarning: unclosed file <_io.BufferedRandom name=6>
  outcome.errors.clear()
F:\Program Files\Anaconda3\lib\unittest\case.py:628: ResourceWarning: unclosed file <_io.BufferedRandom name=7>
  outcome.errors.clear()
F:\Program Files\Anaconda3\lib\unittest\case.py:628: ResourceWarning: unclosed file <_io.BufferedRandom name=8>
  outcome.errors.clear()

**Comment by dennybritz** [comment]
Sorry, but we haven't tested this on windows and can't provide support for it. You'd need to debug this yourself. In theory it should work on Windows, but there may be a few things that just work differently. For example, in your case it seems to be a permission error

**Comment by GuohongLi** [comment]
@dennybritz  On linux, I met the same problem. some info as blow, and I wonder why it needs to open url when evaluation since my runtime env cannot reach network.
INFO:tensorflow:Starting evaluation at 2017-03-27-06:27:27
I tensorflow/core/common_runtime/gpu/gpu_device.cc:975] Creating TensorFlow device (/gpu:0) -> (device: 0, name: Tesla K40m, pci bus id: 0000:84:00.0)
W tensorflow/core/framework/op_kernel.cc:993] Out of range: Reached limit of 1
         [[Node: parallel_read_1/filenames/limit_epochs/CountUpTo = CountUpTo[T=DT_INT64, _class=["loc:@parallel_read_1/filenames/limit_epochs/epochs"], limit=1, _device="/job:localhost/replica:0/task:0/cpu:0"](parallel_read_1/filenames/limit_epochs/epochs)]]
Traceback (most recent call last):
  File "/home/img/liguohong/tool/tensorflow1.0.org/lib/python2.7/site-packages/tensorflow/python/ops/script_ops.py", line 82, in __call__
    ret = func(*args)
  File "/home/img/liguohong/tool/tensorflow1.0.org/lib/python2.7/site-packages/seq2seq/seq2seq/metrics/metric_specs.py", line 156, in _py_func
    return self.metric_fn(sliced_hypotheses, sliced_references)
  File "/home/img/liguohong/tool/tensorflow1.0.org/lib/python2.7/site-packages/seq2seq/seq2seq/metrics/metric_specs.py", line 181, in metric_fn
    return bleu.moses_multi_bleu(hypotheses, references, lowercase=False)
  File "/home/img/liguohong/tool/tensorflow1.0.org/lib/python2.7/site-packages/seq2seq/seq2seq/metrics/bleu.py", line 51, in moses_multi_bleu
    "https://raw.githubusercontent.com/moses-smt/mosesdecoder/"
  File "/home/img/liguohong/tool/tensorflow1.0.org/lib/python2.7/urllib.py", line 93, in urlretrieve
    return _urlopener.retrieve(url, filename, reporthook, data)
  File "/home/img/liguohong/tool/tensorflow1.0.org/lib/python2.7/urllib.py", line 239, in retrieve
    fp = self.open(url, data)
  File "/home/img/liguohong/tool/tensorflow1.0.org/lib/python2.7/urllib.py", line 207, in open
    return getattr(self, name)(url)
  File "/home/img/liguohong/tool/tensorflow1.0.org/lib/python2.7/urllib.py", line 436, in open_https
    h.endheaders(data)
  File "/home/img/liguohong/tool/tensorflow1.0.org/lib/python2.7/httplib.py", line 954, in endheaders
    self._send_output(message_body)
  File "/home/img/liguohong/tool/tensorflow1.0.org/lib/python2.7/httplib.py", line 814, in _send_output
    self.send(msg)
  File "/home/img/liguohong/tool/tensorflow1.0.org/lib/python2.7/httplib.py", line 776, in send
    self.connect()

**Comment by GuohongLi** [comment]
@dennybritz  I have figured out, just ignore it.

**Comment by yanghoonkim** [comment]
what was the problem? @GuohongLi  
Is it the similar problem with mine ? #266

**Comment by gigibang** [comment]
Could you explain the issue and solution? Thanks. I have the same problem. @GuohongLi

**Comment by neerajks** [comment]
@GuohongLi Hi, I am facing the same problem. Could you help with the work around / solution to the problem.

**Comment by RuoqiLiu** [comment]
hi i am facing this problem in win10, do you find a solution?

**Comment by newmluser** [comment]
Is there any solution for this
