### ISSUE TITLE
Internal: Failed to run py callback pyfunc_7

### ISSUE THREAD

**Issue by ultralisksu** [google/seq2seq#77]
Hi,
I am running the code using default configuration (nmt_small.yaml, changed the size of hidden layer from 128 to 50) using TITANX. The first 1000 training steps are good. But then the evaluation failed with the follow errors:

tensorflow/core/framework/op_kernel.cc:993] Internal: Failed to run py callback pyfunc_2: see error log.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/script_ops.py", line 82, in __call__
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/script_ops.py", line 82, in __call__
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/script_ops.py", line 82, in __call__
    ret = func(*args)
  File "/home/ultralisksu/host/seq2seq/seq2seq/metrics/metric_specs.py", line 156, in _py_func
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/script_ops.py", line 82, in __call__
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/script_ops.py", line 82, in __call__
    ret = func(*args)
  File "/home/ultralisksu/host/seq2seq/seq2seq/metrics/metric_specs.py", line 156, in _py_func
    ret = func(*args)
  File "/home/ultralisksu/host/seq2seq/seq2seq/metrics/metric_specs.py", line 156, in _py_func
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/script_ops.py", line 82, in __call__
    return self.metric_fn(sliced_hypotheses, sliced_references)
  File "/home/ultralisksu/host/seq2seq/seq2seq/metrics/metric_specs.py", line 206, in metric_fn
    return self.metric_fn(sliced_hypotheses, sliced_references)

I attached the full logs.
[log.log.txt](https://github.com/google/seq2seq/files/852809/log.log.txt)

Thanks

**Comment by dennybritz** [comment]
Thanks for reporting. This happened due to the recent additional of ROUGE recall scores and some edge case. Shoudl be fixed ith #94.
