### ISSUE TITLE
find an error when run command:python -m unittest seq2seq.test.pipeline_test 

### ISSUE THREAD

**Issue by manene** [google/seq2seq#80]
I tensorflow/core/common_runtime/gpu/gpu_device.cc:975] Creating TensorFlow device (/gpu:0) -> (device: 0, name: Tesla M40 24GB, pci bus id: 0000:04:00.0)
INFO:tensorflow:Restored model from /tmp/tmpzF6STH/model.ckpt-50
W tensorflow/core/framework/op_kernel.cc:993] Out of range: Reached limit of 1
         [[Node: parallel_read_1/filenames/limit_epochs/CountUpTo = CountUpTo[T=DT_INT64, _class=["loc:@parallel_read_1/filenames/limit_epochs/epochs"], limit=1, _device="/job:localhost/replica:0/task:0/c
pu:0"](parallel_read_1/filenames/limit_epochs/epochs)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_35_parallel_read/common_queue' is closed and has insufficient elements (requested 1, current size 0)
         [[Node: parallel_read/common_queue_Dequeue = QueueDequeueV2[component_types=[DT_STRING, DT_STRING], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](parallel_read/common_queue)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_35_parallel_read/common_queue' is closed and has insufficient elements (requested 1, current size 0)
         [[Node: parallel_read/common_queue_Dequeue = QueueDequeueV2[component_types=[DT_STRING, DT_STRING], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](parallel_read/common_queue)]]
a a a a 泣 泣 泣 泣 泣 泣 泣 泣 泣 泣 泣 泣 泣 泣 泣 泣 泣 泣 泣 泣 泣 泣 泣 泣 泣 泣 泣 泣 泣 泣 泣 泣 泣 泣 泣 泣 泣 泣 泣 泣 泣 泣 泣 泣 泣 泣 泣 泣 泣 泣 泣 泣 泣 泣 泣 泣 泣 泣 泣 泣 泣 泣 泣 泣 泣
泣 泣 泣 泣 泣 泣 泣 泣 泣 泣 泣 泣 泣 泣 泣 泣 泣 泣 泣 泣 泣 泣 泣 泣 泣 泣 泣 泣 泣 泣 泣
a a a a a a a a a 泣 泣 泣 泣 泣 泣 泣 泣 泣 泣 泣 泣 泣 泣 泣 泣 泣 泣 泣 泣 泣 泣 泣 泣 泣 泣 泣 泣 泣 泣 泣 泣 泣 泣 泣 泣 泣 泣 泣 泣 泣 泣 泣 泣 泣 泣 泣 泣 泣 泣 泣 泣 泣 泣 泣 泣 泣 泣 泣 泣 泣 泣
泣 泣 泣 泣 泣 泣 泣 泣 泣 泣 泣 泣 泣 泣 泣 泣 泣 泣 泣 泣 泣 泣 泣 泣 泣 泣 泣 泣 泣
E
======================================================================
ERROR: test_train_infer (seq2seq.test.pipeline_test.PipelineTest)
Tests training and inference scripts.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "seq2seq/test/pipeline_test.py", line 184, in test_train_infer
    infer_script.main([])
  File "~/seq2seq/bin/infer.py", line 125, in main
    sess.run([])
  File "/usr/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 462, in run
    run_metadata=run_metadata)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 786, in run
    run_metadata=run_metadata)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 744, in run
    return self._sess.run(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 899, in run
    run_metadata=run_metadata))
  File "seq2seq/tasks/dump_attention.py", line 126, in after_run
    _create_figure(fetches)
  File "seq2seq/tasks/dump_attention.py", line 58, in _create_figure
    fig = plt.figure(figsize=(8, 8))
  File "/usr/lib64/python2.7/site-packages/matplotlib/pyplot.py", line 535, in figure
    **kwargs)
  File "/usr/lib64/python2.7/site-packages/matplotlib/backends/backend_tkagg.py", line 81, in new_figure_manager
    return new_figure_manager_given_figure(num, figure)
  File "/usr/lib64/python2.7/site-packages/matplotlib/backends/backend_tkagg.py", line 89, in new_figure_manager_given_figure
    window = Tk.Tk()
  File "/usr/lib64/python2.7/lib-tk/Tkinter.py", line 1745, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
TclError: no display name and no $DISPLAY environment variable

----------------------------------------------------------------------
Ran 2 tests in 25.226s

FAILED (errors=1)

**Comment by dennybritz** [comment]
```
self.tk = _tkinter.create
```

Seems to be related to your matplotlib installation. Check out the documentation, it's discussed there: https://google.github.io/seq2seq/getting_started/#incorrect-matploblib-backend
