### ISSUE TITLE
Installation on Windows Machine

### ISSUE THREAD

**Issue by vyraun** [google/seq2seq#91]
Hi

I have a windows machine, Conda env for Python 3.5, TF installed. When I run the unit test, I get:

`python -m unittest seq2seq.test.pipeline_test`
```
I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\stream_executor\dso_loader.cc:128] successfully opened CUDA library cublas64_80.dll locally
I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\stream_executor\dso_loader.cc:128] successfully opened CUDA library cudnn64_5.dll locally
I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\stream_executor\dso_loader.cc:128] successfully opened CUDA library cufft64_80.dll locally
I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\stream_executor\dso_loader.cc:128] successfully opened CUDA library nvcuda.dll locally
I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\stream_executor\dso_loader.cc:128] successfully opened CUDA library curand64_80.dll locally
E
======================================================================
ERROR: seq2seq (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: seq2seq
Traceback (most recent call last):
  File "C:\Program Files\Anaconda2\envs\py35\lib\unittest\loader.py", line 153, in loadTestsFromName
    module = __import__(module_name)
  File "C:\Users\vyraun\seq2seq\seq2seq\__init__.py", line 26, in <module>
    from seq2seq import decoders
  File "C:\Users\vyraun\seq2seq\seq2seq\decoders\__init__.py", line 17, in <module>
    from seq2seq.decoders.rnn_decoder import *
  File "C:\Users\vyraun\seq2seq\seq2seq\decoders\rnn_decoder.py", line 33, in <module>
    from seq2seq.encoders.rnn_encoder import _default_rnn_cell_params
  File "C:\Users\vyraun\seq2seq\seq2seq\encoders\__init__.py", line 17, in <module>
    import seq2seq.encoders.rnn_encoder
  File "C:\Users\vyraun\seq2seq\seq2seq\encoders\rnn_encoder.py", line 27, in <module>
    from seq2seq.training import utils as training_utils
  File "C:\Users\vyraun\seq2seq\seq2seq\training\__init__.py", line 17, in <module>
    from seq2seq.training import hooks
  File "C:\Users\vyraun\seq2seq\seq2seq\training\hooks.py", line 30, in <module>
    from tensorflow.python.training.basic_session_run_hooks import SecondOrStepTimer  # pylint: disable=E0611
ImportError: cannot import name 'SecondOrStepTimer'


----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (errors=1)
```

Thanks

**Comment by dennybritz** [comment]
Hi, thanks for reporting. There are two things:

1. I think you are using an outdated TF version
2. Unfortunately we cannot provide support for Windows. We haven't tested on Windows and even though it should work you would need to debug issues yourself. Sorry about that.

**Comment by vyraun** [comment]
@dennybritz Thanks for the reply. I was using an older TF version, although upgraded TF (1.0.1) is also giving errors. Good to know that (2), will switch to Ubuntu if debugging doesn't help.

**Comment by wolfshow** [comment]
@vyraun the problem is tf.contrib on windows does not complete.
